# 3300_Project (c) by Brian Richardson, Ethan Briggs, Jordan Camden, and Thomas Gherna
#
# 3300_Project is licensed under a
# Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
#
# You should have received a copy of the license along with this
# work. If not, see <https://creativecommons.org/licenses/by-nc-sa/4.0/>.
# Generated by Django 5.0.6 on 2024-06-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0002_mountain_lat_mountain_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
