# Generated by Django 5.0.6 on 2024-06-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0002_mountain_lat_mountain_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
