# Generated by Django 5.0.7 on 2024-07-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0004_mountain_pass_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountain',
            name='resort_url',
            field=models.URLField(blank=True),
        ),
    ]
