# Generated by Django 5.0.6 on 2024-07-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0005_mountain_resort_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountain',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
