# Generated by Django 5.0.7 on 2024-07-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0006_mountain_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
