# Generated by Django 5.0.7 on 2024-07-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0008_rename_image_url_mountain_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountain',
            name='image_name',
        ),
        migrations.AddField(
            model_name='mountain',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
